### ISSUE TITLE
Update to latest template

### ISSUE THREAD

**Issue by m-mohr** [stac-extensions/tiled-assets#3]
- Add contributing chapter
- Check that stac_extensions is checked in Collections, too
- Update remark config / remove remarkignore
- ...

**Comment by constantinius** [comment]
@m-mohr 

Can we simply pull from the template? Or do we have to do this manually?

**Comment by m-mohr** [comment]
Unfortunately, it seems the way templates work on GitHub is that you need to add the changes manually.

**Comment by constantinius** [comment]
Done with #6
