### ISSUE TITLE
fix uses of stac_extension shortnames in examples

### ISSUE THREAD

**Issue by philvarner** [stac-extensions/tiled-assets#4]

**Comment by constantinius** [comment]
@philvarner 

I don't quite understand what is to do here. Which shortnames are you referring to? The `eo` for example?

**Comment by m-mohr** [comment]
Yes, the shortnames for extensions (e.g. eo, view, sar, ...) have all been removed and need to be URLs to the schemas now (e.g. https://stac-extensions.github.io/eo/v1.0.0/schema.json for eo)
