### ISSUE TITLE
Validation issue with schema.json stac_extension's URL

### ISSUE THREAD

**Issue by PanierAvide** [stac-extensions/tiled-assets#9]
Hello,

I'm trying to make the [API I'm working on](https://gitlab.com/geovisio/api) tested against STAC specs using [STAC API Validator](https://github.com/stac-utils/stac-api-validator). I'm having a similar issue with this extension as I had on perspective-imagery : https://github.com/stac-extensions/perspective-imagery/issues/9

I use this extension for describing tiled geolocated pictures, the URL to extension is set in my items' `stac_extensions` field. The only URL I found to use is `https://raw.githubusercontent.com/stac-extensions/tiled-assets/main/json-schema/schema.json`, as the schema isn't available on `https://stac-extensions.github.io/tiled-assets/v1.0.0/schema.json`. But, in the JSON schema, the STAC extension URL [should match the `stac-extensions.github.io` URL](https://github.com/stac-extensions/tiled-assets/blob/main/json-schema/schema.json#L57). This causes issues against the validator :

- If I use working URL, validator gives error because schema is not fully validated
- If I use the `stac-extensions.github.io` URL, validator can't find the extension's schema, then fails

Would it be possible to find a solution for this ? Either removing the `stac_extension` requirement in `schema.json`, or publish the existing version on stac-extensions.github.io.

Best regards.

**Comment by Scartography** [comment]
Missing 404 of this extension for the  stac-extensions url: https://stac-extensions.github.io/tiled-assets/v1.0.0/schema.json

Same as above.

**Comment by constantinius** [comment]
v1.0.0 is now released and https://stac-extensions.github.io/tiled-assets/v1.0.0/schema.json is now available
